"""extend course table

Revision ID: 21f7cd768a8f
Revises: 11cfde6e852d
Create Date: 2018-01-12 11:26:55.583009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f7cd768a8f'
down_revision = '11cfde6e852d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('course', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'updated_at')
    op.drop_column('course', 'created_at')
    # ### end Alembic commands ###
